name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: |
          pip install pytest

      - name: Ejecutar pruebas
        run: |
          pytest

      - name: Generar sitio estático (solo ejemplo)
        run: |
          mkdir build
          echo "<h1>Sitio desde CI</h1>" > build/index.html

      - name: Subir artefacto para Pages
        uses: actions/upload-artifact@v4
        with:
          name: github-pages     # 👈 este nombre es crucial
          path: build            # 👈 carpeta a desplegar
          retention-days: 1
