name: CI Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: pip install pytest

      - name: Ejecutar pruebas
        run: pytest

      - name: Generar contenido del sitio
        run: |
          mkdir -p build
          echo "<!DOCTYPE html>
          <html>
          <head>
            <title>Mi Sitio</title>
          </head>
          <body>
            <h1>Sitio desplegado</h1>
            <p>Versión: ${{ github.sha }}</p>
          </body>
          </html>" > build/index.html

      - name: Subir artefacto para Pages
        uses: actions/upload-pages-artifact@v2  # Versión correcta para Pages
        with:
          path: build/
