name: CI Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: pip install pytest

      - name: Ejecutar pruebas
        run: pytest

      - name: Generar contenido del sitio
        run: |
          mkdir -p build
          echo "<h1>Desplegado desde CI</h1>" > build/index.html

      - name: Subir artefacto
        uses: actions/upload-pages-artifact@v2  # Cambiado a upload-pages-artifact
        with:
          path: build/
