name: CI + Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: |
          pip install pytest

      - name: Ejecutar pruebas
        run: |
          pytest

      - name: Generar sitio estático (ejemplo)
        run: |
          mkdir build
          echo "<h1>Hola desde GitHub Pages</h1>" > build/index.html

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v3

      - name: Subir archivos del sitio
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./build
          retention-days: 1

      - name: Desplegar en Pages
        uses: actions/deploy-pages@v2
