name: CI Pipeline

on: 
  push:
    branches: [ main, master ]  # Solo se activa en estas ramas

jobs:
  build-and-preview:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Versión específica recomendada

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Ejecutar tests
        run: pytest

      - name: Construir sitio
        run: |
          mkdir -p public
          echo "<!doctype html>
          <html>
          <head>
            <meta charset='utf-8'>
            <title>GitHub Pages</title>
          </head>
          <body>
            <h1>Despliegue exitoso</h1>
            <p>Commit SHA: ${{ github.sha }}</p>
            <p>Fecha: $(date)</p>
          </html>" > public/index.html

      - name: Subir artefacto
        uses: actions/upload-pages-artifact@v2  # ÚNICA ACCIÓN RECOMENDADA PARA PAGES
        with:
          path: '.'  # Ruta exacta del contenido
          retention-days: 1
