name: CI Pipeline

on: 
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          
      - name: Ejecutar tests
        run: pytest --tb=short
        continue-on-error: false
        
      - name: Construir sitio
        run: |
          mkdir -p public
          cat > public/index.html << 'EOF'
          <!doctype html>
          <html>
          <head>
            <meta charset='utf-8'>
            <title>GitHub Pages - Despliegue Exitoso</title>
            <style>
              body { font-family: Arial, sans-serif; margin: 40px; }
              h1 { color: #0366d6; }
              .info { background: #f6f8fa; padding: 20px; border-radius: 6px; }
            </style>
          </head>
          <body>
            <h1>🚀 Despliegue exitoso</h1>
            <div class="info">
              <p><strong>Commit SHA:</strong> ${{ github.sha }}</p>
              <p><strong>Fecha:</strong> $(date -u +"%Y-%m-%d %H:%M:%S UTC")</p>
              <p><strong>Rama:</strong> ${{ github.ref_name }}</p>
              <p><strong>Repositorio:</strong> ${{ github.repository }}</p>
            </div>
          </body>
          </html>
          EOF
          
      - name: Subir artefacto para Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
